#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/vk-turn-wrapper
    procd_set_param respawn 3 15 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
    logger -t vk-turn "Service started"
}

stop_service() {
    logger -t vk-turn "Stopping"
    procd_kill
}
